/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import control.ServicoController;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Ricardo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    private DefaultComboBoxModel[] model = new DefaultComboBoxModel[6]; 
    
    private DefaultListModel listModel;
    private ServicoController servico;
    private int minhasTentativas = 0;
    public TelaPrincipal() {

        initComponents();
        listModel = new DefaultListModel();
        
        for(int i = 0; i < 6; i++)
        {
            model[i] = new DefaultComboBoxModel();
        }
        for(int i = 10; i >= 0; i--)
        {
            for(int j = 0; j < 6; j++){
                model[j].addElement(i);
            }
        }
        cbAcao.setModel(model[0]);
        cbAventura.setModel(model[1]);
        cbFiccao.setModel(model[2]);
        cbTerror.setModel(model[3]);
        cbGuerra.setModel(model[4]);
        cbComedia.setModel(model[5]);
        listModel.setSize(30);
        jList1.setModel(listModel);
                
        pbStatusNegociacao.setValue(0);
        try{servico = new ServicoController();
        }catch(Exception ex){}
                

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pbStatusNegociacao = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbAcao = new javax.swing.JComboBox<>();
        cbAventura = new javax.swing.JComboBox<>();
        cbFiccao = new javax.swing.JComboBox<>();
        cbTerror = new javax.swing.JComboBox<>();
        cbGuerra = new javax.swing.JComboBox<>();
        cbComedia = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        tfNomePessoa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taNegociacao = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Status da Negociação:");

        jButton1.setText("Iniciar Negociação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Envolvidos:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Genero do Filme");

        jLabel4.setText("Ação");

        jLabel5.setText("Aventura");

        jLabel6.setText("Ficção Científica");

        jLabel7.setText("Terror");

        jLabel8.setText("Guerra");

        jLabel9.setText("Comédia");

        cbAcao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbAventura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbFiccao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTerror.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbGuerra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbComedia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Duração do Filme");

        jLabel11.setText("Longo");

        jCheckBox1.setText(">= 120 min");

        jLabel13.setText("Médio");

        jCheckBox3.setText("> 90 min < 120");

        jLabel14.setText("Curto");

        jCheckBox4.setText("<= 90");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Diretores");

        jLabel15.setText("Diretores:");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Escolher");

        jLabel16.setText("Diretores escolhidos como preferidos:");

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setText("Nome:");

        jLabel18.setText("Espaço de Negociação");

        taNegociacao.setColumns(20);
        taNegociacao.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        taNegociacao.setRows(5);
        jScrollPane2.setViewportView(taNegociacao);

        jMenu1.setText("Sobre");

        jMenuItem1.setText("Sobre a aplicação");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel8)
                                    .addGap(4, 4, 4)
                                    .addComponent(cbGuerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(4, 4, 4)
                                    .addComponent(cbComedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel7)
                                    .addGap(4, 4, 4)
                                    .addComponent(cbTerror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel5)
                                    .addGap(4, 4, 4)
                                    .addComponent(cbAventura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(4, 4, 4)
                                    .addComponent(cbFiccao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(cbAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(6, 6, 6)
                                    .addComponent(jCheckBox1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(6, 6, 6)
                                    .addComponent(jCheckBox3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(6, 6, 6)
                                    .addComponent(jCheckBox4))))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel2))))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pbStatusNegociacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(tfNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jButton1))))
                    .addComponent(jLabel18)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(156, 156, 156)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4))
                            .addComponent(cbAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(cbAventura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(cbFiccao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7))
                            .addComponent(cbTerror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tfNomePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pbStatusNegociacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButton1))
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbGuerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9))
                            .addComponent(cbComedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel11))
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel13))
                            .addComponent(jCheckBox3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel14))
                            .addComponent(jCheckBox4))
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tfNomePessoa.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor, insira um nome para iniciar a negociação");
            return;
        }
        
        try{
            
            servico.enviarInicializacao(tfNomePessoa.getText());
            DefaultListModel modelo = (DefaultListModel) jList1.getModel();
            modelo.clear();
            String clientes = servico.receberClientes();
            System.out.println(clientes);
            String[] lista = clientes.split(";");
            for(String nome: lista){                
                if(!listModel.contains(nome) && nome != "" && !nome.isEmpty() && nome!=" "){
                    System.out.println(nome);
                    modelo.addElement(nome);
                }
            }
            
            
            taNegociacao.append("Iniciando negociação..\n");
            Runnable runnable = new Runnable() {
                public void run(){
                    try{ 
                        String clientes = servico.receberClientes();
                        System.out.println(clientes);
                        int siz = clientes.split(";").length;
                        System.out.println(" " + siz);
                        while(siz < 2){
                            taNegociacao.append("Aguardando entrar um novo negociador...\n");
                            Thread.sleep(3000);
                            clientes = servico.receberClientes();
                            System.out.println(" " + siz);
                            System.out.println(" " + clientes);
                            siz = clientes.split(";").length;
                            
                        }
                        String[] lista = clientes.split(";");
                        for(String nome: lista){                
                             if(!listModel.contains(nome) && nome != "" && !nome.isEmpty() && nome!=" "){
                                 System.out.println(nome);
                                 modelo.addElement(nome);
                             }
                         }
                        taNegociacao.append("Negociantes entraram na negociação...\n");
//                        Thread.currentThread().interrupt();
//                        adicionarMnesagens(1);

                        int total = Integer.parseInt(servico.iteracoes());
                        while(total <= 10){
                            String acao = servico.receberAcao();
                            
                            if(acao.equals("aceito")){
                                taNegociacao.append("A negociação foi aceita \n");
                                break;
                            }
                            if(acao.equals("vazia")){
                                servico.enviarAcao(generoMaior());
                            }
                            else {
                                try {
                                    String[] dividida = acao.split(";");
                                    if(dividida.length > 0 ){
                                        System.out.println(" " + dividida.length + " " + dividida[0]);
                                        String[] co = dividida[0].split(":");
                                        System.out.println(" " + co[0] + " " + co[1]);
                                        int meuValor = getValorByGenero(co[0]);
                                        System.out.println("--> " + meuValor + " " + co[1]);
                                        if(meuValor >= Integer.parseInt(co[1])){
                                            taNegociacao.append("Eu aceito a negociação\n");
                                            servico.enviarAcao("aceito");
                                            JOptionPane.showMessageDialog(null, "Genero escolhido: " + co[0]);
                                            break;
                                        }
                                        else {
                                            servico.enviarAcao(generoMaior());
                                            if(minhasTentativas >= 2){
                                                servico.enviarAcao("Terror");
                                            }else if(minhasTentativas >= 4){
                                                servico.enviarAcao("Comedia");
                                            }else if(minhasTentativas >= 6){
                                                servico.enviarAcao("Guerra");
                                            }
                                        }
                                        switch(Integer.parseInt(servico.iteracoes())){
                                            case 1:
                                                
                                                break;
                                            case 2:
                                                break;
                                            case 3:
                                                break;
                                            case 4:
                                                break;
                                            case 5:
                                                break;
                                            case 6:
                                                break;
                                            case 7:
                                                break;
                                            case 8:
                                                break;
                                            case 9:
                                                break;
                                            case 10:
                                                break;
                                                
                                        }
                                        
                                    }
                                }catch(Exception ex){
                                    System.out.println("" + ex.getMessage());
                                }
                                
                                
                            }
                            if(!acao.equals("vazia"))
                                taNegociacao.append("Eu quero " + acao + "\n");
                            
                            Thread.sleep(2000);
                            
                            pbStatusNegociacao.setValue(total*10);
                            
                            total = Integer.parseInt(servico.iteracoes());
                            
                        }
                        
                        servico.enviarDesligamento(tfNomePessoa.getText());
                        Thread.currentThread().interrupt();
                    }
                    catch(Exception ex){
                        System.out.println(" " + ex.getMessage());
                    }
                }
            };
            Thread t = new Thread(runnable);
            t.start();
            
        }
        catch (Exception ex)
        {
            System.out.println("Error: " +ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private int getValorByGenero(String genero) {
        int retorno = -1;
        if("Acao".equals(genero))
            retorno = (int) cbAcao.getSelectedItem();
        if("Aventura".equals(genero))
            retorno = (int) cbAventura.getSelectedItem();
        if("Ficcao".equals(genero))
            retorno = (int) cbFiccao.getSelectedItem();
        if("Terror".equals(genero))
            retorno =  (int) cbTerror.getSelectedItem();
        if("Guerra".equals(genero))
            retorno = (int) cbGuerra.getSelectedItem();
        if("Comedia".equals(genero))
            retorno = (int) cbComedia.getSelectedItem();
        return retorno;
    }
    private String generoMaior(){
        String generoMaior = "";
        int generoMaiorInt = -1;
        int acao = (int) cbAcao.getSelectedItem();
        int aventura = (int) cbAventura.getSelectedItem();
        int ficcao = (int) cbFiccao.getSelectedItem();
        int terror =  (int) cbTerror.getSelectedItem();
        int guerra = (int) cbGuerra.getSelectedItem();
        int comedia = (int) cbComedia.getSelectedItem();

        
        if( acao > generoMaiorInt){
            generoMaiorInt = acao;
            generoMaior = "Acao";
        }
        if( aventura > generoMaiorInt){
            generoMaiorInt = aventura;
            generoMaior = "Aventura";
        }
        if( ficcao > generoMaiorInt){
            generoMaiorInt = ficcao;
            generoMaior = "Ficcao";
        }
        if( terror > generoMaiorInt){
            generoMaiorInt = terror;
            generoMaior = "Terror";
        }
        if( guerra > generoMaiorInt){
            generoMaiorInt = guerra;
            generoMaior = "Guerra";
        }
        if( comedia > generoMaiorInt){
            generoMaiorInt = comedia;
            generoMaior = "Comedia";
        }

        return (generoMaior + ":" + generoMaiorInt);
        
    }
    
    public void adicionarMnesagens(int rand) throws InterruptedException{
        
        if(rand == 1){
            taNegociacao.append("Eu quero terror");
            Thread.sleep(1000);
            taNegociacao.append("Eu quero terror longo");
            Thread.sleep(1300);
            taNegociacao.append("Eu aceito a negociacao");
            Thread.sleep(1500);
        }

        if(rand == 2){
            taNegociacao.append("Eu quero aventura");
            Thread.sleep(1200);
            taNegociacao.append("Eu quero aventura");
            Thread.sleep(1600);
            taNegociacao.append("Eu aceito a negociacao");
        }

        if(rand == 3){
            taNegociacao.append("Eu quero comedia");
            Thread.sleep(1000);
            taNegociacao.append("Eu quero terror");
            Thread.sleep(1200);
            taNegociacao.append("Eu quero acao");
            Thread.sleep(1400);
            taNegociacao.append("Eu quero aventura");
            Thread.sleep(1500);
            taNegociacao.append("Eu quero ficcao");
            Thread.sleep(1600);
            taNegociacao.append("Eu quero ficcao medio");
            Thread.sleep(1200);
            taNegociacao.append("Eu quero aventura medio");
            Thread.sleep(1300);
            taNegociacao.append("Eu rejeito a negociacao");
        }

    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try{
            if(!tfNomePessoa.getText().isEmpty()){
                servico.enviarDesligamento(tfNomePessoa.getText());
            }
        }
        catch(Exception ex){}
                        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAcao;
    private javax.swing.JComboBox<String> cbAventura;
    private javax.swing.JComboBox<String> cbComedia;
    private javax.swing.JComboBox<String> cbFiccao;
    private javax.swing.JComboBox<String> cbGuerra;
    private javax.swing.JComboBox<String> cbTerror;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar pbStatusNegociacao;
    private javax.swing.JTextArea taNegociacao;
    private javax.swing.JTextField tfNomePessoa;
    // End of variables declaration//GEN-END:variables
}
